namespace SamplyGame
{
	// Perhaps this file can be auto-generated by T4 script
	public static class Assets
	{
		public static class Fonts
		{
			public const string Font = "Fonts/Font.ttf";
		}
	}
}
